name: qr_reader_hive2
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  appsize: ^1.2.0
  bloc: ^8.1.0
  data_persistence:
    path: packages/data_persistence
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  go_router: ^4.3.0
  google_maps_flutter: ^2.1.12
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  path: ^1.8.1
  path_provider: ^2.0.11
  provider: ^6.0.3
  url_launcher: ^6.1.5

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
